name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - alpha
      - beta

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Update release-plz Configuration for Non-Main Branches
        if: env.BRANCH_NAME != 'main'
        run: |
          echo ${{ env.BRANCH_NAME }}
          echo {{ env.BRANCH_NAME }}
          sed "s/{{package}}/${{ env.BRANCH_NAME }}-{{package}}/g" release-plz.toml.template > .release-plz.toml

          cat release-plz.toml
        shell: bash

      - name: Write release-plz config for Main Branch
        if: env.BRANCH_NAME == 'main'
        run: |
          cp .release-plz.toml.template .release-plz.toml
          cat release-plz.toml
        shell: bash

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
