name: Version Bump

# prevent concurrent version bumps
concurrency:
  group: "version-bump"

on:
  # workflow dispatch allows us to generate a new version without having to push a commit
  workflow_dispatch:
    inputs:
      channel:
        description: 'The release-channel branch to bump'
        required: true
        options:
          - alpha
          - beta
          - rc
  push:
    branches:
    # run for everything that gets into main
      - main
    

env:
  RELEASE_PLZ_BIN_URL: https://github.com/MarcoIeni/release-plz/releases/download/release-plz-v0.3.43/release-plz-x86_64-unknown-linux-gnu.tar.gz
  WORKFLOW_URL: https://github.com/maidsafe/safe_network/actions/runs

jobs:
  bump_version:
    if: |
      github.repository_owner == 'maidsafe' &&
      !startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          token: ${{ secrets.VERSION_BUMP_COMMIT_PAT }}
          ref: ${{ github.event.inputs.channel || 'main' }}

      - name: Get the SHA of the last release commit
        id: get-sha
        run: echo "sha=$(git log --grep='chore(release):' -n 1 --pretty=format:"%H")" >> $GITHUB_ENV

      - name: Wait for release workflow to complete
        uses: mostafahussein/workflow-watcher@v1.0.0
        # Don't fail the whole run if this step fails
        # this action will fail if the previous workflows failed or was skipped,
        # which isn't helpful
        continue-on-error: true
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          repository-name: ${{ github.repository }}
          repository-owner: ${{ github.repository_owner }}
          head-sha: ${{ env.sha }}
          base-branch: ${{ github.event.inputs.channel || 'main' }}
          polling-interval: 60

      - name: Fetch the latest code from the specified branch
        run: git pull origin ${{ github.event.inputs.channel || 'main' }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      # It's possible to `cargo install` release-plz, but it's very slow to compile on GHA infra.
      # Therefore we just pull the binary from the Github Release.
      - name: install release-plz
        shell: bash
        run: |
          curl -L -O $RELEASE_PLZ_BIN_URL
          tar xvf release-plz-x86_64-unknown-linux-gnu.tar.gz
          rm release-plz-x86_64-unknown-linux-gnu.tar.gz
          sudo mv release-plz /usr/local/bin
      - shell: bash
        # if we're running a workflow for a release channel, pass that in here, otherwise the script assumes we're on main
        run: ./resources/scripts/bump_version.sh ${{ github.event.inputs.channel }}
      - name: push version bump commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.VERSION_BUMP_COMMIT_PAT }}
          branch: ${{ github.event.inputs.channel || 'main' }}
          tags: true
      - name: post notification to slack on failure
        if: ${{ failure() }}
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_GH_ACTIONS_WEBHOOK_URL }}
          SLACK_MESSAGE: "Please check the logs for the run at ${{ env.WORKFLOW_URL }}/${{ github.run_id }}"
          SLACK_TITLE: "Version Bumping Failed"
